### ISSUE TITLE
*olx* in domains-blocklist-local-additions.txt blocks a legit series of latin-american buy-and-sell websites

### ISSUE THREAD

**Issue by cypherpunk1984** [quindecim/block#1]
https://www.olx.com
https://www.olx.com.ar (Argentina)
https://www.olx.com.br (Brazil)
https://www.olx.com.co (Colombia)
etc. etc. (there is one for pretty much every latin-american country)

Same thing with the especialized ones for cars:
https://www.olxautos.com.ar
etc. etc.

Mercadolibre (owned by ebay) is the most used website for buying and selling stuff in latin-america, the 2nd most important one is OLX.

**Comment by quindecim** [comment]
Thanks for the report, fixed in https://github.com/quindecim/block/commit/500c457d0c329fe53025456dad09752bca8b3deb.
